# Generated by Django 5.2 on 2025-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstonefinalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(),
        ),
    ]
